export const keywords = [// --- General/Universal Keywords ---
"Results-driven",
"Goal-oriented",
"Detail-oriented",
"Problem-solving",
"Critical thinking",
"Communication (written & verbal)",
"Teamwork",
"Collaboration",
"Leadership",
"Management",
"Project Management",
"Time Management",
"Organizational Skills",
"Adaptability",
"Flexibility",
"Initiative",
"Innovation",
"Creativity",
"Customer Service",
"Client Relations",
"Strategic Planning",
"Decision-making",
"Negotiation",
"Conflict Resolution",
"Process Improvement",
"Efficiency",
"Accuracy",
"Analytical Skills",
"Research Skills",
"Technical Skills",
"Data Analysis",
"Reporting",
"Documentation",
"Training",
"Mentoring",
"Budget Management",
"Cost Reduction",
"Quality Assurance",
"Compliance",
"Risk Management",
"Performance Management",
"Stakeholder Management",
"Cross-functional Teams",
"Continuous Improvement",
"Best Practices",
"KPIs (Key Performance Indicators)",
"ROI (Return on Investment)",
"SOPs (Standard Operating Procedures)",

// --- Skills (Adapt to Industry/Role) ---
// **REPLACE WITH SPECIFIC SKILLS LISTED IN THE JOB DESCRIPTION**
"Software Development", // Example - Replace with actual languages/frameworks
"Data Science",         // Example - Replace with specific tools/techniques
"Marketing Automation", // Example - Replace with platforms
"Financial Modeling",   // Example
"Cloud Computing",      // Example- AWS, Azure, GCP
"Cybersecurity",
"Network Administration",
"Database Management",
"Supply Chain Management",
"Human Resources",
"Accounting",
"Salesforce",
"SQL",
"Python",
"Java",
"JavaScript",
"HTML",
"CSS",
"Project Management Methodologies (Agile, Scrum, Waterfall)",
"SEO (Search Engine Optimization)",
"SEM (Search Engine Marketing)",
"CRM (Customer Relationship Management)",
"ERP (Enterprise Resource Planning)",
"CAD (Computer-Aided Design)",
"CAM (Computer-Aided Manufacturing)",

// --- Action Verbs (Start each bullet point with a strong action verb) ---
"Achieved",
"Developed",
"Managed",
"Led",
"Implemented",
"Increased",
"Decreased",
"Improved",
"Reduced",
"Created",
"Designed",
"Executed",
"Coordinated",
"Collaborated",
"Negotiated",
"Trained",
"Mentored",
"Supervised",
"Oversaw",
"Optimized",
"Analyzed",
"Researched",
"Solved",
"Streamlined",
"Automated",
"Generated",
"Delivered",
"Presented",
"Facilitated",
"Advised",
"Consulted",
"Authored",
"Published",

// --- Industry-Specific Terms (Adapt to the Industry) ---
// **REPLACE WITH INDUSTRY-SPECIFIC JARGON**
"HIPAA Compliance",      // Healthcare example
"Sarbanes-Oxley (SOX)", // Finance example
"GMP (Good Manufacturing Practices)", // Manufacturing
"FDA Regulations",
"Clinical Trials",
"Machine Learning",    // Tech Example
"Blockchain",
"Renewable Energy",
"LEED Certification",   // Construction
"Six Sigma",           // Process Improvement

// --- Education & Certifications (List all relevant ones) ---
"Bachelor's Degree",
"Master's Degree",
"Doctorate",
"MBA",
"PMP (Project Management Professional)",
"Six Sigma Green Belt",
"Six Sigma Black Belt",
"CPA (Certified Public Accountant)",
"PHR (Professional in Human Resources)",
"SPHR (Senior Professional in Human Resources)",
"AWS Certified",
"Microsoft Certified",
"CISSP (Certified Information Systems Security Professional)",

//---Soft Skills
"Interpersonal skills",
"Active Listening",
"Empathy",
"Emotional Intelligence",
"Patience",
"Persuasion",
"Influence",
"Negotiation",
"Public Speaking",
"Presentation Skills",
"Networking",
"Diplomacy",
"Conflict Resolution",
"Mediation",
"Coaching",
"Mentoring",
"Team Building",
"Facilitation",
"Collaboration",
"Relationship Management",
"Building Rapport",
"Cross-cultural Communication",
"Diversity and Inclusion",
"Adaptability",
"Flexibility",
"Resilience",
"Stress Management",
"Time Management",
"Prioritization",
"Organization",
"Planning",
"Problem-solving",
"Critical Thinking",
"Decision Making",
"Creativity",
"Innovation",
"Resourcefulness",
"Initiative",
"Proactiveness",
"Self-Motivation",
"Leadership",
"Vision",
"Strategic Thinking",
"Delegation",
"Empowerment",
"Accountability",
"Integrity",
"Ethics",
"Professionalism",
"Customer Focus",
"Client Relations",
"Service Orientation",
"Communication",
"Written Communication",
"Verbal Communication",
"Presentation Skills",
"Active Listening",
"Feedback Skills",
"Negotiation Skills",
"Persuasion Skills",
"Conflict Resolution",
"Collaboration",
"Teamwork",
"Leadership",
"Motivation",
"Problem-solving",
"Decision-making",
"Time Management",
"Organizational Skills",
"Adaptability",
"Flexibility",
"Interpersonal skills"
];

